SOURCES += app/AccountInterface.py \
        app/AttendanceInterface.py \
        app/HomeInterface.py \
        app/main_window.py \
        app/ScheduleInterface.py \
        app/ScoreInterface.py \
        app/SettingInterface.py \
        app/ToolBoxInterface.py \
        app/TrayInterface.py \
        app/sub_interfaces/AutoJudgeInterface.py \
        app/sub_interfaces/AvatarDialog.py \
        app/sub_interfaces/ChangeTermDialog.py \
        app/sub_interfaces/EmptyRoomInterface.py \
        app/sub_interfaces/EncryptDialog.py \
        app/sub_interfaces/ExportCalendarDialog.py \
        app/sub_interfaces/JudgeAllOptionInterface.py \
        app/sub_interfaces/JudgeOptionInterface.py \
        app/sub_interfaces/LessonConflictDialog.py \
        app/sub_interfaces/LessonDetailDialog.py \
        app/sub_interfaces/LoginInterface.py \
        app/sub_interfaces/NoticeChoiceInterface.py \
        app/sub_interfaces/NoticeInterface.py \
        app/sub_interfaces/NoticeRuleInterface.py \
        app/sub_interfaces/NoticeSettingInterface.py \
        app/sub_interfaces/ResetVisitorIdDialog.py \
        app/sub_interfaces/RuleSetInterface.py \
        app/sub_interfaces/ScoreDetailDialog.py \
        app/sub_interfaces/TermStartTimeDialog.py \
        app/sub_interfaces/VerifyCodeDialog.py \
        app/sub_interfaces/WebVPNConvertInterface.py \
        app/components/CardManagerDialog.py \
        app/components/CustomMessageBox.py \
        app/components/MultiSelectionComboBox.py \
        app/components/NoticeCard.py \
        app/components/NoticeRuleCard.py \
        app/components/NoticeSourceCard.py \
        app/components/ProgressInfoBar.py \
        app/components/RuleLine.py \
        app/components/ScheduleTable.py \
        app/cards/copyable_switch_card.py \
        app/cards/custom_color_setting_card.py \
        app/cards/custom_switch_card.py \
        app/cards/link_card.py \
        app/cards/pure_lesson_card.py \
        app/cards/tool_card.py \
        app/threads/AttendanceFlowThread.py \
        app/threads/CFEmptyRoomThread.py \
        app/threads/DownloadUpdateThread.py \
        app/threads/EmptyRoomThread.py \
        app/threads/ExamScheduleThread.py \
        app/threads/GraduateScheduleThread.py \
        app/threads/GraduateScoreThread.py \
        app/threads/HolidayThread.py \
        app/threads/LoginThreads.py \
        app/threads/JudgeThread.py \
        app/threads/NoticeThread.py \
        app/threads/ProcessWidget.py \
        app/threads/ScheduleAttendanceMonitorThread.py \
        app/threads/ScheduleAttendanceThread.py \
        app/threads/ScheduleThread.py \
        app/threads/ScoreThread.py \
        app/threads/UpdateThread.py \

TRANSLATIONS += assets/i18n/XJTUToolBox.en_US.ts
